version: "3"
services:
  app:
    image: golang:1.14.6-alpine3.11
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/kiddy-line-processor/main.go
    links:
      - redis
      - line-provider
    environment:
      UPD_INTERVAL_FOOTBALL: 3
      UPD_INTERVAL_SOCCER: 2
      UPD_INTERVAL_BASEBALL: 5
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_USERNAME:
      DB_PASSWORD:
      DB_HOST:
      DB_PORT: 6379
      LOG_LEVEL: debug
      LINE_PROVIDER_API_URL: http://localhost:8000/api/v1/lines
    ports:
      - "8080:8080"

  redis:
    image: redis:6.0.6-alpine

  line-provider:
    image: antonboom/lines-provider